apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavaliable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: my-app
      spec:
        containers:
          - image: nginx:1.12
            name: nginx
            ports:
              - containerPort: 80
            readinessProbe:
              failureTreshold: 3
              httpGet:
                path: /
                port: 80
              periodSeconds: 10
              successThreshold: 1
              timeoutSecond: 1
            livenessProbe:
              failureTreshold: 3
              httpGet:
                path: /
                port: 80
              periodSeconds: 10
              successThreshold: 1
              timeoutSecond: 1  
              initialDelaySeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                cpu: 100m
                memory: 100Mi